version: "3.8"
services:
  app:
    build:
      context: .
      target: runner
    ports:
      - "9000:9000"
      - "9002:9002"
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:' + (process.env.API_PORT || 9000) + '/health', (r) => {if (r.statusCode !== 200) process.exit(1)})",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
